declare module 'lucide-react' {
    import { FC, SVGProps } from 'react';
    export interface IconProps extends SVGProps<SVGSVGElement> {
        color?: string;
        size?: string | number;
        strokeWidth?: string | number;
        absoluteStrokeWidth?: boolean;
    }
    export type Icon = FC<IconProps>;

    export const MapPin: Icon;
    export const Menu: Icon;
    export const X: Icon;
    export const Facebook: Icon;
    export const Instagram: Icon;
    export const Twitter: Icon;
    export const Mail: Icon;
    export const ChevronDown: Icon;
    export const Calendar: Icon;
    export const User: Icon;
    export const Star: Icon;
    export const Navigation: Icon;
    export const LayoutDashboard: Icon;
    export const Users: Icon;
    export const Settings: Icon;
    export const LogOut: Icon;
    export const ArrowRight: Icon;
    export const ArrowLeft: Icon;
    export const Lock: Icon;
    export const CheckCircle: Icon;
    export const XCircle: Icon;
    export const Clock: Icon;
    export const Phone: Icon;
    export const Plus: Icon;
    export const Minus: Icon;
    export const Search: Icon;
    export const ScanLine: Icon;
    export const CheckCircle2: Icon;
    export const CreditCard: Icon;
    export const TrendingUp: Icon;
    export const Crown: Icon;
    export const Award: Icon;
    export const Medal: Icon;
    export const Brain: Icon;
    export const Dumbbell: Icon;
    export const Moon: Icon;
    export const Wind: Icon;
    export const Shield: Icon;
    export const ShieldCheck: Icon;
    export const Music: Icon;
    export const Coffee: Icon;
    export const Activity: Icon;
    export const Check: Icon;
    export const Trash2: Icon;
    export const AlertTriangle: Icon;
    export const UtensilsCrossed: Icon;
    export const Sparkles: Icon;
    export const Wine: Icon;
    export const Play: Icon;
    export const Sofa: Icon;
    export const Droplets: Icon;
    export const ChevronLeft: Icon;
    export const ChevronRight: Icon;
    export const Maximize2: Icon;
    export const Camera: Icon;
    export const Zap: Icon;
    export const Info: Icon;
    export const Share2: Icon;
    export const Gift: Icon;
    export const Copy: Icon;
}
